// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCC.ProjetoCaprino.Data;

#nullable disable

namespace TCC.ProjetoCaprino.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TCC.ProjetoCaprino.Domain.Entities.CaprinoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brinco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PesoAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RacaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Sexo")
                        .HasColumnType("bit");

                    b.Property<Guid>("TipoDeCricaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RacaId");

                    b.HasIndex("TipoDeCricaoId");

                    b.ToTable("Caprino", (string)null);
                });

            modelBuilder.Entity("TCC.ProjetoCaprino.Domain.Entities.EventoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoDeEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("TCC.ProjetoCaprino.Domain.Entities.HistoricoDoCaprinoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaprinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantidadeDeAlimento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantidadeDeLeite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TipoDeAlimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VacinaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CaprinoId");

                    b.HasIndex("EventoId");

                    b.HasIndex("TipoDeAlimentoId");

                    b.HasIndex("VacinaId");

                    b.ToTable("HistoricoDoCaprino");
                });

            modelBuilder.Entity("TCC.ProjetoCaprino.Domain.Entities.RacaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Raca", (string)null);
                });

            modelBuilder.Entity("TCC.ProjetoCaprino.Domain.Entities.TipoDeAlimentoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoDeAlimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoDeAlimento", (string)null);
                });

            modelBuilder.Entity("TCC.ProjetoCaprino.Domain.Entities.TipoDeCriacaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoDeCriacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoDeCriacao", (string)null);
                });

            modelBuilder.Entity("TCC.ProjetoCaprino.Domain.Entities.VacinaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoDeVacina")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Vacina", (string)null);
                });

            modelBuilder.Entity("TCC.ProjetoCaprino.Domain.Entities.CaprinoEntity", b =>
                {
                    b.HasOne("TCC.ProjetoCaprino.Domain.Entities.RacaEntity", "Raca")
                        .WithMany()
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCC.ProjetoCaprino.Domain.Entities.TipoDeCriacaoEntity", "TipoDeCricao")
                        .WithMany()
                        .HasForeignKey("TipoDeCricaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Raca");

                    b.Navigation("TipoDeCricao");
                });

            modelBuilder.Entity("TCC.ProjetoCaprino.Domain.Entities.HistoricoDoCaprinoEntity", b =>
                {
                    b.HasOne("TCC.ProjetoCaprino.Domain.Entities.CaprinoEntity", "Caprino")
                        .WithMany("Historico")
                        .HasForeignKey("CaprinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCC.ProjetoCaprino.Domain.Entities.EventoEntity", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCC.ProjetoCaprino.Domain.Entities.TipoDeAlimentoEntity", "TipoDeAlimento")
                        .WithMany()
                        .HasForeignKey("TipoDeAlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCC.ProjetoCaprino.Domain.Entities.VacinaEntity", "Vacina")
                        .WithMany()
                        .HasForeignKey("VacinaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caprino");

                    b.Navigation("Evento");

                    b.Navigation("TipoDeAlimento");

                    b.Navigation("Vacina");
                });

            modelBuilder.Entity("TCC.ProjetoCaprino.Domain.Entities.CaprinoEntity", b =>
                {
                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
